name: rcl
version: 0.1.0.0
github: freckle/rcl
license: MIT
author: Patrick Brisbin
maintainer: freckle-engineering@renaissance.com
copyright: 2020 Freckle Engineering

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see <https://github.com/freckle/rcl#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - http-client
    - http-conduit
    - http-types
    - optparse-applicative
    - text
    - these
    - unordered-containers
    - vector

executables:
  rcl:
    main: Main.hs
    source-dirs: executables
    dependencies:
      - rcl
      - optparse-applicative
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
