name: rcl
version: 0.1.0.0
github: freckle/rcl
license: MIT
author: Patrick Brisbin
maintainer: freckle-engineering@renaissance.com
copyright: 2020 Freckle Engineering

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see <https://github.com/freckle/rcl#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies


library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - errors
    - extra
    - hashable-time
    - http-client
    - http-conduit
    - http-types
    - lucid
    - megaparsec
    - mmark
    - optparse-applicative
    - scotty
    - text
    - these
    - transformers
    - unordered-containers
    - vector

executables:
  rcl-web:
    main: Main.hs
    source-dirs: rcl-web
    dependencies:
      - aeson
      - containers
      - lucid
      - megaparsec
      - mmark
      - rcl
      - scotty
      - text
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  rcl-stack-dependencies:
    main: Main.hs
    source-dirs: rcl-stack-dependencies
    dependencies:
      - aeson
      - text
      - yaml
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson
      - hspec
      - QuickCheck
      - rcl
      - unordered-containers
